"""added Type to monster/char

Revision ID: 4586abfaa762
Revises: d7f3db7e1c2a
Create Date: 2023-09-20 16:09:32.464447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4586abfaa762'
down_revision = 'd7f3db7e1c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('chars', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
