"""Added Status to Monsters


Revision ID: 82ab1f9c5ef3
Revises: 4586abfaa762
Create Date: 2023-09-21 22:39:34.437131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ab1f9c5ef3'
down_revision = '4586abfaa762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
