"""init

Revision ID: be987b7e14f5
Revises: 4c19b861d2e2
Create Date: 2023-09-15 14:25:18.537143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be987b7e14f5'
down_revision = '4c19b861d2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treasures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stat_buff', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stat_potency', sa.Integer(), nullable=True))
        batch_op.drop_column('ability_potency')
        batch_op.drop_column('ability_buff')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treasures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ability_buff', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('ability_potency', sa.INTEGER(), nullable=True))
        batch_op.drop_column('stat_potency')
        batch_op.drop_column('stat_buff')

    # ### end Alembic commands ###
