"""init

Revision ID: d7ed4eefac1a
Revises: 
Create Date: 2023-09-15 12:54:48.581385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ed4eefac1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('status_effect', sa.Boolean(), nullable=True),
    sa.Column('effect_hostile', sa.Boolean(), nullable=True),
    sa.Column('effect_version', sa.String(), nullable=True),
    sa.Column('effect_type', sa.String(), nullable=True),
    sa.Column('effect_range', sa.Integer(), nullable=True),
    sa.Column('effect_ability', sa.String(), nullable=True),
    sa.Column('effect_power', sa.Integer(), nullable=True),
    sa.Column('damaging', sa.Boolean(), nullable=True),
    sa.Column('damage_type', sa.String(), nullable=True),
    sa.Column('damage_range', sa.Integer(), nullable=True),
    sa.Column('damage_ability', sa.String(), nullable=True),
    sa.Column('level_req', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('str_growth', sa.Integer(), nullable=False),
    sa.Column('agi_growth', sa.Integer(), nullable=False),
    sa.Column('con_growth', sa.Integer(), nullable=False),
    sa.Column('mag_growth', sa.Integer(), nullable=False),
    sa.Column('res_growth', sa.Integer(), nullable=False),
    sa.Column('spd_growth', sa.Integer(), nullable=False),
    sa.Column('hp_growth', sa.Integer(), nullable=False),
    sa.Column('mp_growth', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('img_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('mp', sa.Integer(), nullable=False),
    sa.Column('str', sa.Integer(), nullable=False),
    sa.Column('agi', sa.Integer(), nullable=False),
    sa.Column('con', sa.Integer(), nullable=False),
    sa.Column('mag', sa.Integer(), nullable=False),
    sa.Column('res', sa.Integer(), nullable=False),
    sa.Column('spd', sa.Integer(), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('lvl', sa.Integer(), nullable=False),
    sa.Column('damage_type', sa.String(), nullable=False),
    sa.Column('damage_ability', sa.String(), nullable=False),
    sa.Column('damage_range', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treasures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('consumable_effect', sa.String(), nullable=True),
    sa.Column('consumable_potency', sa.Integer(), nullable=True),
    sa.Column('ability_buff', sa.String(), nullable=True),
    sa.Column('ability_potency', sa.Integer(), nullable=True),
    sa.Column('reduction', sa.Boolean(), nullable=True),
    sa.Column('damage_reduction', sa.Integer(), nullable=True),
    sa.Column('boost', sa.Boolean(), nullable=True),
    sa.Column('damage_boost', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('char_name', sa.String(length=20), nullable=False),
    sa.Column('char_class', sa.Integer(), nullable=False),
    sa.Column('str', sa.Integer(), nullable=False),
    sa.Column('agi', sa.Integer(), nullable=False),
    sa.Column('con', sa.Integer(), nullable=False),
    sa.Column('mag', sa.Integer(), nullable=False),
    sa.Column('res', sa.Integer(), nullable=False),
    sa.Column('spd', sa.Integer(), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('lvl', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('mp', sa.Integer(), nullable=False),
    sa.Column('wep_id', sa.Integer(), nullable=False),
    sa.Column('arm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arm_id'], ['treasures.id'], name=op.f('fk_chars_arm_id_treasures')),
    sa.ForeignKeyConstraint(['char_class'], ['classes.id'], name=op.f('fk_chars_char_class_classes')),
    sa.ForeignKeyConstraint(['wep_id'], ['treasures.id'], name=op.f('fk_chars_wep_id_treasures')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_ability_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], name=op.f('fk_class_ability_associations_ability_id_abilities')),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_class_ability_associations_class_id_classes')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monster_ability_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.Column('ability_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], name=op.f('fk_monster_ability_associations_ability_id_abilities')),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_monster_ability_associations_monster_id_monsters')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monster_environment_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], name=op.f('fk_monster_environment_associations_environment_id_environment')),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], name=op.f('fk_monster_environment_associations_monster_id_monsters')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('char_1', sa.Integer(), nullable=True),
    sa.Column('char_2', sa.Integer(), nullable=True),
    sa.Column('char_3', sa.Integer(), nullable=True),
    sa.Column('char_4', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['char_1'], ['chars.id'], name=op.f('fk_users_char_1_chars')),
    sa.ForeignKeyConstraint(['char_2'], ['chars.id'], name=op.f('fk_users_char_2_chars')),
    sa.ForeignKeyConstraint(['char_3'], ['chars.id'], name=op.f('fk_users_char_3_chars')),
    sa.ForeignKeyConstraint(['char_4'], ['chars.id'], name=op.f('fk_users_char_4_chars')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot_1', sa.Integer(), nullable=True),
    sa.Column('slot_2', sa.Integer(), nullable=True),
    sa.Column('slot_3', sa.Integer(), nullable=True),
    sa.Column('slot_4', sa.Integer(), nullable=True),
    sa.Column('slot_5', sa.Integer(), nullable=True),
    sa.Column('slot_6', sa.Integer(), nullable=True),
    sa.Column('slot_7', sa.Integer(), nullable=True),
    sa.Column('slot_8', sa.Integer(), nullable=True),
    sa.Column('slot_9', sa.Integer(), nullable=True),
    sa.Column('slot_10', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['slot_1'], ['treasures.id'], name=op.f('fk_inventories_slot_1_treasures')),
    sa.ForeignKeyConstraint(['slot_10'], ['treasures.id'], name=op.f('fk_inventories_slot_10_treasures')),
    sa.ForeignKeyConstraint(['slot_2'], ['treasures.id'], name=op.f('fk_inventories_slot_2_treasures')),
    sa.ForeignKeyConstraint(['slot_3'], ['treasures.id'], name=op.f('fk_inventories_slot_3_treasures')),
    sa.ForeignKeyConstraint(['slot_4'], ['treasures.id'], name=op.f('fk_inventories_slot_4_treasures')),
    sa.ForeignKeyConstraint(['slot_5'], ['treasures.id'], name=op.f('fk_inventories_slot_5_treasures')),
    sa.ForeignKeyConstraint(['slot_6'], ['treasures.id'], name=op.f('fk_inventories_slot_6_treasures')),
    sa.ForeignKeyConstraint(['slot_7'], ['treasures.id'], name=op.f('fk_inventories_slot_7_treasures')),
    sa.ForeignKeyConstraint(['slot_8'], ['treasures.id'], name=op.f('fk_inventories_slot_8_treasures')),
    sa.ForeignKeyConstraint(['slot_9'], ['treasures.id'], name=op.f('fk_inventories_slot_9_treasures')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inventories_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventories')
    op.drop_table('users')
    op.drop_table('monster_environment_associations')
    op.drop_table('monster_ability_associations')
    op.drop_table('class_ability_associations')
    op.drop_table('chars')
    op.drop_table('treasures')
    op.drop_table('saves')
    op.drop_table('monsters')
    op.drop_table('environment')
    op.drop_table('classes')
    op.drop_table('abilities')
    # ### end Alembic commands ###
