"""added status to char

Revision ID: d7f3db7e1c2a
Revises: cf85353d109a
Create Date: 2023-09-20 12:19:22.611760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f3db7e1c2a'
down_revision = 'cf85353d109a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chars', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
