"""added effect_duration, etc

Revision ID: f35ac84e1139
Revises: 82ab1f9c5ef3
Create Date: 2023-09-22 00:34:03.038841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35ac84e1139'
down_revision = '82ab1f9c5ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effect_duration', sa.Integer(), nullable=True))

    with op.batch_alter_table('chars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_duration', sa.Integer(), nullable=True))

    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monsters', schema=None) as batch_op:
        batch_op.drop_column('status_duration')

    with op.batch_alter_table('chars', schema=None) as batch_op:
        batch_op.drop_column('status_duration')

    with op.batch_alter_table('abilities', schema=None) as batch_op:
        batch_op.drop_column('effect_duration')

    # ### end Alembic commands ###
